### ISSUE TITLE
First event to share in Facebook doesn't show the image

### ISSUE THREAD

**Issue by Rynaro** [huacnlee/social-share-button#101]
When the share event is called to create a Facebook content share, the image doesn't show. But, if the window is closed, and reopened by a new event call, the image shows as expected.

I think this behavior is related with Rails asset cache system.

**Comment by doncadavona** [comment]
I think it's Facebook's problem. Facebook first scrapes the image and fails to sync immidiately on first share. https://www.facebook.com/help/community/question/?id=10200708365214182

**Comment by Rynaro** [comment]
I check a workaround fix. 
Only need to set `og width / height` attributes to force the Facebook service to get image and renderize on share image attach. :smiley:

**Comment by doncadavona** [comment]
Great. As Facebook seems to be the only that can fix this. Please let us know if you have a workaround.

**Comment by Rynaro** [comment]
To solve the_pseudo_  problem, you only need to add image size rules to limit the image size.
I put a example below:

```html
<meta property="og:image:width" content="450">
<meta property="og:image:height" content="450">
```

I think, Facebook `og tags` can't read the image first time when Rails provide, but in a second request, the image has been delivered by Rails Asset in previous request, and then Facebook can get the image.

**Comment by doncadavona** [comment]
I have not tested it yet. But adding an image size does not seem to fix it in theory because Facebook somehow admits or ignores the case that it must be shared or scraped at least ones to work.

**Comment by Rynaro** [comment]
I have some web apps that I used this gem to include the "social sharing" function. And I had the problem of facebook sharing without the "page image" in first attempt, but in a second attempt, the image shows in "share container".
And after the adjustment on image sizing rules in head of HTML, the "problem" has solved. And keep working in all web apps in production mode.
