### ISSUE TITLE
Facebook and Google+ links don't work?

### ISSUE THREAD

**Issue by benlieb** [huacnlee/social-share-button#102]
I'm installing this for the first time today and am very disappointed that the facebook and google+ links don't seem to work properly. The other buttons seem to work properly. Am I missing something?

<img width="532" alt="screen shot 2016-10-16 at 15 18 04" src="https://cloud.githubusercontent.com/assets/634562/19420176/fd6efabe-93b3-11e6-8c75-6bbdf6777cc4.png">
<img width="622" alt="screen shot 2016-10-16 at 15 20 04" src="https://cloud.githubusercontent.com/assets/634562/19420178/10586624-93b4-11e6-88bf-c790e4a67c04.png">

**Comment by alexsnchz** [comment]
I was having the same problem but was because I were in localhost using my computer ip instead and worked fine. Hope that can help you too
