### ISSUE TITLE
URLS with params not displaying correctly in Facebook

### ISSUE THREAD

**Issue by thebenjy** [huacnlee/social-share-button#104]
I have a social share button. I've set the :url  to www.url.com?r=123
it works in twitter and email 
it does not work on facebook, google+ and linkedin. the url in the pop-up is www.url.com e.g. missing the r parameter?

known issue or reason?

thanks for for a v. useful gem!

Ben

**Comment by huacnlee** [comment]
https://github.com/huacnlee/social-share-button/issues/102
