### ISSUE TITLE
translation go wack when not present?

### ISSUE THREAD

**Issue by benlieb** [huacnlee/social-share-button#107]
<a class="ssb-icon ssb-reddit" data-site="reddit" href="#" onclick="return SocialShareButton.share(this);" rel="nofollow " **title="<span class=" translation_missing"**="">Share To"&gt;</a>

**Comment by huacnlee** [comment]
You need configure your Rails config/application.rb

```rb
config.i18n.fallbacks = true
```

**Comment by benlieb** [comment]
good call!
