### ISSUE TITLE
text appeared on the icon

### ISSUE THREAD

**Issue by bogdan8** [huacnlee/social-share-button#109]
after installing gem on the icon appeared text as it take?
![2016-11-16 11 06 25](https://cloud.githubusercontent.com/assets/12710600/20341018/02612bcc-abed-11e6-9ced-693d09ea59d3.png)

**Comment by huacnlee** [comment]
There is have not I18n file of you application locale.

https://github.com/huacnlee/social-share-button/tree/master/config/locales

**Comment by bogdan8** [comment]
Thank you all works
