### ISSUE TITLE
social icon can't show

### ISSUE THREAD

**Issue by haitaochen** [huacnlee/social-share-button#113]
why not the icon displayed,in my html source code,Here already exists
```
<a rel="nofollow " data-site="facebook" class="ssb-icon ssb-facebook" onclick="return SocialShareButton.share(this);" title="Share to Facebook" href="#"></a>
```
like above ,but the icon width and height are all 0*0,and if I miss something?

**Comment by huacnlee** [comment]
Which browser and version?

**Comment by haitaochen** [comment]
Google chrome 54.0.2840.98 (64-bit),btw excited to receive your reply

**Comment by haitaochen** [comment]
I just try to create a new application,it works,and I don't know why,sorry for my odd error and thanks for the gem,it's useful for me!
