### ISSUE TITLE
Facebook Share doesn't work

### ISSUE THREAD

**Issue by NancyLuLay** [huacnlee/social-share-button#119]
The Facebook Share btn doesn't work. 
Is anyone having the same problem? I have also added Twitter, Pinterest and Linkedin and they all work except for Facebook.

**Comment by alexmorral** [comment]
Are you running on localhost? 
Take a look at #102

**Comment by NancyLuLay** [comment]
Yes, I will check once it's deployed.
Thank you!

**Comment by kashishkhullar** [comment]
Did it work, NancyLuLay, after deployment? I am having the same problem , facebook is not working for me as well.
