### ISSUE TITLE
TypeError: $(...).data is not a function

### ISSUE THREAD

**Issue by wirates** [huacnlee/social-share-button#14]
I am trying to use the gem in my rails app with Ruby version 1.9.2-p320 & Rails 3.1.1, all is working well but when I click on any of the icon for share then it wouldn't do anything. I have inspected it & found the below issue 

TypeError: $(...).data is not a function            social...?body=1 (line 10)
site = $(el).data('site');

I am trying to resolve but no luck.

**Comment by huacnlee** [comment]
jQuery
