### ISSUE TITLE
not working on Facebook

### ISSUE THREAD

**Issue by liulupeng1987** [huacnlee/social-share-button#141]
Hi,
   I am a new guy on ruby on rails.
   I use rails 5. I use this gem.
   It works well on twitter, linkedin, but not work on facebook?
   When I share my page to facebook, it said
-----
Sorry, something went wrong.
We're working on getting this fixed as soon as we can.
Go Back
-----

   How can I solve this problem?
   Thanks very much!

**Comment by Dhug95** [comment]
I have the same problem. Not working with facebook and rails 5. When I click on the button I stay on the same page I was before, I don't even get the popup

**Comment by Brennaleker** [comment]
Experiencing the same issue with rails 5

**Comment by robcole** [comment]
@Brennaleker @Dhug95 @liulupeng1987 - Can you give a bit more detail about the error and how to replicate it? Including major / minor version number, how you're triggering the error, other gems you have installed, etc.

FWIW @huacnlee - I'm on Rails 5.1 and haven't encountered any errors with Facebook sharing.

**Comment by ryankc33** [comment]
Same here. The modal opens and just says 

Sorry, something went wrong.
We're working on getting this fixed as soon as we can.

Without any error messages or logs. Not sure how to be more specific.

**Comment by knoxjeffrey** [comment]
I had the same issue when I was first testing the gem. However, specifying a url fixed the issue for me. I guess Facebook was trying to request my localhost as the url to share which causes the error.

**Comment by davidherer** [comment]
Hi, seems to not be fixed. I still get the error.

**Comment by austinarchibald** [comment]
Yes, I am having the same issue. Both in development and in production. I am specifying a URL and it still says `Sorry, something went wrong`

Any one figured out a fix?

**Comment by trungnguyencmu** [comment]
+1

**Comment by kul1** [comment]
+1

**Comment by dmilicic** [comment]
+1

**Comment by aharonhillel** [comment]
+1

**Comment by cojimene** [comment]
I solved adding the desc key to the helper eg: 
`<%= social_share_button_tag @product.name, desc: @product.description %>`
However only works with real url, in development environment you can try adding url key.

**Comment by rakesh-kumar** [comment]
Working for me thanks. @cojimene

**Comment by LauraDFLD** [comment]
Still doesn't work for me with the desc key and real url

**Comment by renatamarques97** [comment]
same problem here
