### ISSUE TITLE
Facebook button error message

### ISSUE THREAD

**Issue by samuelpbowman** [huacnlee/social-share-button#149]
When following the guide to insert social share buttons, the Facebook button generates
![image](https://user-images.githubusercontent.com/8527824/31241494-fe04dd10-a9d1-11e7-8a04-8fe74565aa6c.png)
Gemfile contains
`gem social-share-button`
The config/social_share_button.rb was modified as such
```
SocialShareButton.configure do |config|
  config.allow_sites = %w(twitter facebook google_plus 
                           tumblr email linkedin reddit)
end
```
and I inserted into the ERB file
`<%= social_share_button_tag(@post.title) %>`
Is this an error in my implementation, the gem, or on Facebook's end? Thanks for any assistance.

**Comment by activestylus** [comment]
I am also experiencing this issue. No matter what I do Facebook throws that same error

**Comment by Afoster2** [comment]
Same problem here on my end.

**Comment by martinbortowski** [comment]
Having the same problem as well.

**Comment by juniorjp** [comment]
Same problem too.

**Comment by samuelpbowman** [comment]
Since this appears widespread, I've forked the repository and will submit a pull request and link it here if I find a solution.

**Comment by maland** [comment]
same here

**Comment by juniorjp** [comment]
I've added a non blank data-url to the parent tag and the error is gone. But now the share window just closes and nothing happens.

**Comment by rafikiass** [comment]
Same problem.  - Any solution to this issue?

**Comment by samuelpbowman** [comment]
I’m working on one; if anybody wants to get in on this, I can add you as a contributor on my fork.

**Comment by samuelpbowman** [comment]
For the Gitter users, feel free to visit this room to contribute 
Join the chat in social-share-button/potential-fix-ideas
https://gitter.im/social-share-button_sams-fork/potential-fix-ideas?utm_source=ios&utm_medium=link&utm_campaign=ios-share-link

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rafikiass** [comment]
actually adding a description fixes the issue. 
```
<%= social_share_button_tag(micropost.content, :url => micropost_url(micropost), desc: micropost.content)%>
```

**Comment by activestylus** [comment]
@rafikiass That did the trick - thanks!

**Comment by Afoster2** [comment]
No luck for me. Instead, doesn't fix the facebook issue and it added the copy to the view again.

**Comment by activestylus** [comment]
@Afoster2  Another potential issue in development mode: if Facebook sees your link is localhost:3000 it will throw that same error. Try throwing in a real domain/working URL and see if that helps. This should not be an issue in production

**Comment by savanr** [comment]
@activestylus You are right. You can use http://lvh.me:3000 for development environment. Production will work fine as it uses real world name. Also don't forget to add "desc: @post.description".

**Comment by Afoster2** [comment]
@activestylus @savanr Yes! Ya'll were right. Locally the facebook share button was still giving me problems. But in production, it works just fine! Thanks for your help!

**Comment by fourcolors** [comment]
Having the same problem

**Comment by bishisht** [comment]
@rafikiass Thanks mate :+1: problem solved :)

**Comment by hopewise** [comment]
@Afoster2 Have you found a solution?

**Comment by seanfcarroll** [comment]
This can be closed, see linked PR.
