### ISSUE TITLE
Social-Share-Button visible but redirecting to same page

### ISSUE THREAD

**Issue by Shaheen-Al-Asadi** [huacnlee/social-share-button#179]
Im trying to add share buttons to a blog page, ive included the js/css portions and in my view i have:

```
<%= social_share_button_tag(@blog_post.title,
                                        :url => "mysite.com/blog/",
                                        :image => "https://www.mediawiki.org/wiki/Help:Images#/media/File:Example.jpg",
                                        desc: @blog_post.title,
                                        via: "twitterhandle")
%>
```

Now when clicking any of the buttons it redirects to the top of the page:
"http://localhost:3000/blog/some-title" turns into "http://localhost:3000/blog/some-title#"

What am i missing? Is it because I'm testing on a local server?

**Comment by huacnlee** [comment]
Open your Chrome Developer, there must be have some JavaScript error.

**Comment by Shaheen-Al-Asadi** [comment]
![1](https://user-images.githubusercontent.com/17502812/53110994-395f4200-350a-11e9-9fe9-f7e712da5e29.png)

Here is what show up html in inspector, when i click the buttons it just redirects to the top of the page.

**Comment by Shaheen-Al-Asadi** [comment]
Edit:

Nevermind it is working now :)
Our project used a different javascript partial file instead of the standard app/assets/javascripts/application location, i placed "//= require social-share-button" in the correct file and it is working. Thank you for this gem ⭐️
