### ISSUE TITLE
Facebook button's page says "Sorry, something went wrong"

### ISSUE THREAD

**Issue by Randall-Coding** [huacnlee/social-share-button#190]
Facebook share button seems to be malfunctioning.  Leads to this page:

![Screenshot at 11-17-08](https://user-images.githubusercontent.com/39175191/82072888-01f42c80-969e-11ea-8003-293e56726140.png)

The other icons I'm using seem to be functioning (haven't posted to each one, but looks like they are going to login page at least).  

**Browser**
Firefox  76.0.1 and Chrome 79

**Comment by jhonny2pamp** [comment]
up

**Comment by Randall-Coding** [comment]
> up

I'm still getting the same issue, any suggestions?

**Comment by Randall-Coding** [comment]
Latest commit fixed it.  Thanks.

**Comment by Randall-Coding** [comment]
Latest commit fixed it. Thanks.
