### ISSUE TITLE
After sharing content the page is getting closed abruptly 

### ISSUE THREAD

**Issue by AjayROR** [huacnlee/social-share-button#28]
I am using "social-share-button' gem in my rails application (rails 4.0.1), after sharing my Post over social networking sites, the page is getting closed abruptly. 

Any way to customize the redirection path and indicate the same to a valid page with a nice confirmation Message ? 

my View section : 
<%= social_share_button_tag(@blog.name, :url =>"http://192.168.9.10:3000/blogs/") %>

Social_share_button.rb configuration File : 
 
SocialShareButton.configure do |config|
                                 config.allow_sites = %w(twitter facebook google_plus)
end

Any ways to fix this issue ?

**Comment by huacnlee** [comment]
version 0.3.1

It changed the sharing behavior with Popup window
