### ISSUE TITLE
Issues with facebook

### ISSUE THREAD

**Issue by neeraji2it** [huacnlee/social-share-button#33]
I am using your gem for sharing accounts. Here issue with facebook share. It's only taking default images and text to share. I was given exact text what i needs to show in user facebook profile. Let me know about this.

<%= social_share_button_tag("exact text here:", :url => "http://example.herokuapp.com/", :image => "#{@drive.photo.url(:original)}") %>

Please help here. Thanks in advance.

**Comment by CutAndFold** [comment]
I've tried using this fix but I am unable to get an image to post to facebook. I am trying to share a URL and share an image preview. Could use some help to get this working.

**Comment by DownUndered** [comment]
Unfortunatelly, vrybas's fix do not solve the problem as facebook still shows the first picture it gets from the website. I have checked it's URL passed and it seems OK but the issue still there.
