### ISSUE TITLE
How to remove the link text "Share to>" from buttons?

### ISSUE THREAD

**Issue by pablosalgadom** [huacnlee/social-share-button#36]
Hello everyone, 

  I'm using this gem but when the icons link to share have a text "Share to>" and i don't know to remove, i've tryed removing line "share_to: Share to %{name}" from the "social_share_button.en.yml" but nothing happens.

  I also look into the javascript file, but it isn't there, can someone help me on this?

Thank you!

**Comment by albertopeam** [comment]
Thank you to @pablosalgadom to provide the trick, i also use 'es' and i had the same problem. I think that @huacnlee could add this to the readme to help the users of the gem.
