### ISSUE TITLE
via param is missed for twitte rbutton

### ISSUE THREAD

**Issue by yahor** [huacnlee/social-share-button#43]
https://dev.twitter.com/web/tweet-button#optout
via - Screen name of the user to attribute the Tweet to

**Comment by mikeh0rn** [comment]
@ChuckJHardy @yahor  hey - this is the only post I found on this Issue. How could I possibly implement the "via" fix in my code? right now I have the following. Any advice you may have would be extremely helpful:

<%= social_share_button_tag(@post.text, :url => "http://url.com", via: "mytwitterhandle") %>

**Comment by yahor** [comment]
@mikeh0rn you should try update gem version to "0.1.9"

**Comment by mikeh0rn** [comment]
@yahor Thank you! That did it.
