### ISSUE TITLE
via twitter param doesn't work

### ISSUE THREAD

**Issue by camilledelbos** [huacnlee/social-share-button#52]
In the Readme, a comma is missing before 'via: '
Plus, after the "via" the account name is missing too, there's only the "@".

**Comment by mikeh0rn** [comment]
@cuterxy @camilledelbos @SRDP hey - this is the only post I found on this Issue. How could I possibly implement the "via" fix in my code? right now I have the following. Any advice you may have would be extremely helpful:

<%= social_share_button_tag(@post.text, :url => "http://url.com", via: "mytwitterhandle") %>

**Comment by cuterxy** [comment]
My change have been merged into the master branch. Just check it out and you should get the right output of the 'via' for twitter.

**Comment by mikeh0rn** [comment]
@cuterxy Thank you. Saw your merge and trying via_str instead of via. Is that correct? Would you mind helping me out and providing over a quick example of what I should be doing correctly to populate the twitter handle? There is no other good example of this that is visible to me online.

**Comment by cuterxy** [comment]
Below is my sample:
```
<%= social_share_button_tag h("#{post.title}"), url: show_post_url(post.sid), via: 'ogxio', 'data-twitter-title' => h("#OGX.io #{post.title}") %>
```

**Comment by mikeh0rn** [comment]
@cuterxy Thank you! The problem was I couldn't update the Gem without pointing it to your master branch in the Gemfile. After doing that and running bundle, it works perfectly.

**Comment by josephmallari** [comment]
@mikeh0rn Hey, I'm having the same problem with this. I couldn't update the gem. Can you elaborate when you say "pointing it to your master branch in the Gemfile".

Thanks!

**Comment by mikeh0rn** [comment]
@josephmallari Took me awhile to figure it out but the way I was able to solve my problem so that the "via" parameter worked was by pointing the gemfile to @cuterxy's master branch from his fork of the original gem repo (hope this makes sense). Paste this into your Gemfile exactly and run bundle install from the terminal:

<tt>gem 'social-share-button', '~> 0.1.8', git: 'https://github.com/cuterxy/social-share-button.git'</tt>

Let me know if you're still having any issues.

**Comment by mikeh0rn** [comment]
@josephmallari forgot to mention that by running bundle install, this was the only way I was able to get the gem to use the 0.1.9 version that has the 'via' fix.

**Comment by mikeh0rn** [comment]
@josephmallari any luck?

**Comment by josephmallari** [comment]
@mikeh0rn I was able to point out to the Gemfile but I may need help on the syntax. Do you have a couple of minutes to help me with this? If so, can I email you directly? Thanks!

**Comment by mikeh0rn** [comment]
@josephmallari I'm happy to help you out tomorrow. Email me with all of your questions to this email address: mikelaurencehorn@gmail.com.
