### ISSUE TITLE
via: options not working it appears ampty

### ISSUE THREAD

**Issue by ssoulless** [huacnlee/social-share-button#59]
Hi Im trying to specify the via: option with my twitter username but it does not work

<%= social_share_button_tag(@ofert.title, popup: "true", via: "Mytwitter") %>

when trying to share it show Via in the text of the tweet but does not display anything else...

**Comment by mcadenhe** [comment]
I am having the same issue, i tried following these directions to get it to work (https://github.com/huacnlee/social-share-button/issues/52) but to no avail.

**Comment by haitaochen** [comment]
why not the icon displayed,in my html source code,
```
<a rel="nofollow " data-site="facebook" class="ssb-icon ssb-facebook" onclick="return SocialShareButton.share(this);" title="Share to Facebook" href="#"></a>
```
like above ,but the icon width and height are all 0*0,and if I miss something
