### ISSUE TITLE
Not rendering the buttons properly

### ISSUE THREAD

**Issue by camillavk** [huacnlee/social-share-button#60]
I'm trying to implement the buttons but next to each button it is printing "Share To" href="#">"

<a rel="nofollow " data-site="facebook" class="social-share-button-facebook" onclick="return SocialShareButton.share(this);" title="<span class=" translation_missing"="">Share To" href="#"></a>

How can I stop this happening and render just the buttons?

**Comment by huacnlee** [comment]
You need I18n file

**Comment by andersennl** [comment]
I know this issue was closed some time ago but may I ask how exactly this was solved? I'm currently having the same problem.
