### ISSUE TITLE
How to get large icons

### ISSUE THREAD

**Issue by Padmahas** [huacnlee/social-share-button#66]
Hello, I integrated social-share-button 0.1.8 successfully. However I'd like to get little large icons apart from default icons. Is there is way like by specifying <div class= "social-medium"> ?

And another thing is, in [this link](https://richonrails.com/articles/adding-social-sharing-buttons-to-your-rails-app), it has mentioned that I can use " :url => " to specify a link. But I didn't get what that exactly means. I thought instead of customizing which social sharing sites to be appear in "config/initializers/social_share_button.rb:", I can specifically give "<%= social_share_button_tag("selfstarter", :url => "http://facebook.com") %>". But it is not working as expected.

Thank you.

**Comment by Javingka** [comment]
For your first question, take a look to this closed issue https://github.com/huacnlee/social-share-button/issues/62

**Comment by Padmahas** [comment]
Thank you Javingka, I'll try your solution.

**Comment by huacnlee** [comment]
version 0.3.1 released, now we have SVG version icons.
