### ISSUE TITLE
The image social-share-button.png is not served on production rails 4.2.3

### ISSUE THREAD

**Issue by marvindanig** [huacnlee/social-share-button#67]
It was working earlier, before I updated to rails 4.2.3 from 4.1.3.rc3. 

At the moment the url it is trying to hit is `/assets/sprites/social-share-button.png`, i.e without the fingerprinted key behind it. It should request '/assets/sprites/social-share-button@2x-c947d5e6219bfdd711301498f6c76828.png' instead.

I checked that the 'public/assets/sprites' folder on production has all the fingerprinted sprites, so something must be wrong with path generation. Any fix for this because I don't want to revert my upgrade for this. The images are served in prod mode on my local correctly.

**Comment by huacnlee** [comment]
use new version

**Comment by dehinde007** [comment]
Still not working in production.
