### ISSUE TITLE
Error generating social_share_button

### ISSUE THREAD

**Issue by fanig01** [huacnlee/social-share-button#69]
Include the gem in Gemfile , run bundle install and run rails generate social_share_button:install, it returns an error:
/config/application.rb:10:in `<module:SocialShareButton>': uninitialized constant SocialShareButton::Rails::Application (NameError)
	from /SocialShareButton/config/application.rb:9:in `<top (required)>'
	from /home/user/.rvm/gems/ruby-2.2.1/gems/spring-1.4.1/lib/spring/application.rb:82:in `require'
	from /home/user/.rvm/gems/ruby-2.2.1/gems/spring-1.4.1/lib/spring/application.rb:82:in `preload'
	from /home/user/.rvm/gems/ruby-2.2.1/gems/spring-1.4.1/lib/spring/application.rb:143:in `serve'
	from /home/user/.rvm/gems/ruby-2.2.1/gems/spring-1.4.1/lib/spring/application.rb:131:in `block in run'
	from /home/user/.rvm/gems/ruby-2.2.1/gems/spring-1.4.1/lib/spring/application.rb:125:in `loop'
	from /home/user/.rvm/gems/ruby-2.2.1/gems/spring-1.4.1/lib/spring/application.rb:125:in `run'
	from /home/user/.rvm/gems/ruby-2.2.1/gems/spring-1.4.1/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'

how to solve?

**Comment by huacnlee** [comment]
You have use `SocialShareButton` with you Rails application name, that name is conflict with `social-share-button`!
