### ISSUE TITLE
Facebook share not working while directly using HTML instead of tag.

### ISSUE THREAD

**Issue by aneeshktry** [huacnlee/social-share-button#79]
Hi,

I was trying to use social share button in my project. It was working fine when I  used it directly as a tag it is working.
<%= social_share_button_tag(data.heading, :url => "#{request.base_url}/path", :image => data.image, desc: "some desc" ,:popup => "true") %>

But in a particular scenario I try to use the row html which the tag generate internally, directly in my code as below. Because I am using javascript library handlebars.js to generate html. Inside that we can't use a rails tag. So I tried with direct HTML.

<div class="social-share-button" data-title="{{heading}}" data-img="{{image}}" data-url="{{base}}/news/{{permalink}}" data-desc="{{short_news}}" data-via="">
              <a rel="nofollow " data-site="twitter" class="social-share-button-twitter" onclick="return SocialShareButton.share(this);" title="Share to Twitter" href="#"></a>
              <a rel="nofollow " data-site="facebook" class="social-share-button-facebook" onclick="return SocialShareButton.share(this);" title="Share to Facebook" href="#"></a>
              <a rel="nofollow " data-site="google_plus" class="social-share-button-google_plus" onclick="return SocialShareButton.share(this);" title="Share to Google+" href="#"></a>
              <a rel="nofollow " data-site="pinterest" class="social-share-button-pinterest" onclick="return SocialShareButton.share(this);" title="Share to Pinterest" href="#"></a>
              <a rel="nofollow " data-site="email" class="social-share-button-email" onclick="return SocialShareButton.share(this);" title="Share to Email" href="#"></a>
              <a rel="nofollow " data-site="linkedin" class="social-share-button-linkedin" onclick="return SocialShareButton.share(this);" title="Share to Linkedin" href="#"></a>
            </div>

All other sharing working properly. But when click on face book, pop up is coming and immediately closing it before doing any action. Can any one give a solution.

**Comment by digitalfab** [comment]
I have the same issue. Trying to figure out what's happening.
Have you found a solution by your side?

**Comment by digitalfab** [comment]
OK what happened.
the URL is not encoded correctly.
the correct way to encode the url is CGI::escape("http://blbla.com")
as the Gem encode today the url, only the ':' are encoded and never the '/'

**Comment by digitalfab** [comment]
the release gem 'social-share-button', '~> 0.3.1'
works, without a bug
