### ISSUE TITLE
Social Share Button v0.3.3 Facebook error

### ISSUE THREAD

**Issue by p-guerin** [huacnlee/social-share-button#86]
Hello, 
In the version 0.3.3, facebook share button doesn't work anymore. When i click on it, nothing appears ... only a "#" is insert at the end of the url in my navigator.

Thx for help.

**Comment by hassanse91** [comment]
i have same error , is there any solution for this !!? help and thanks

**Comment by huacnlee** [comment]
Use lower version, 0.3.3 yanked
