### ISSUE TITLE
微信分享有问题

### ISSUE THREAD

**Issue by hw676018683** [huacnlee/social-share-button#87]
图片用的是：`weichat.svg`
social-share-button.coffee[里面](https://github.com/huacnlee/social-share-button/blob/master/app/assets/javascripts/social-share-button.coffee#L48)：判断的是`weixin`
`weichat` != `weixin` 没统一

**Comment by Dameng0803** [comment]
any solutions?

**Comment by Dameng0803** [comment]
link does not work ....

**Comment by liuzhenangel** [comment]
weixin 分享加了 https://res.wx.qq.com/open/js/jweixin-1.0.0.js 还是无法分享

**Comment by songjiayang** [comment]
这个确实有问题依赖， jweixin 主要用于公众号
