### ISSUE TITLE
Facebook share error

### ISSUE THREAD

**Issue by cg5544** [huacnlee/social-share-button#97]
I am unable to share on Facebook using the gem. However, sharing on Twitter and Linkedin works. Has anyone experience the same issue? 

Here is what I keep getting when trying to share on FB:
<img width="554" alt="facebook_share_error2016-09-30_2353" src="https://cloud.githubusercontent.com/assets/5017304/19011599/5af798aa-8769-11e6-85d3-df1527499aa1.png">

**Comment by killerham** [comment]
Its because you're sharing from localhost. When you use a public url it works as expected.
